kafka:
  bootstrap.servers: ${KASHPY_KAFKA_SERVER}
  security.protocol: SASL_SSL
  sasl.mechanisms: PLAIN
  sasl.username: ${KASHPY_KAFKA_USERNAME}
  sasl.password: ${KASHPY_KAFKA_PASSWORD}
  
schema_registry:
  schema.registry.url: ${KASHPY_SCHEMA_REGISTRY_URL}
  basic.auth.credentials.source: USER_INFO
  basic.auth.user.info: ${KASHPY_SCHEMA_REGISTRY_USER_INFO}

kash:
  flush.num.messages: 10000
  flush.timeout: -1.0
  retention.ms: -1
  consume.timeout: 10.0
  enable.auto.commit: true
  session.timeout.ms: 10000
  block.num.retries.int: 50
  block.interval: 0.1
  auto.offset.reset: earliest
  progress.num.messages: 1000
