kafka:
  bootstrap.servers: ${KASHPY_KAFKA_SERVER}
  security.protocol: sasl_plaintext
  sasl.mechanisms: SCRAM-SHA-256
  sasl.username: ${KASHPY_KAFKA_USERNAME}
  sasl.password: ${KASHPY_KAFKA_PASSWORD}

kash:
  flush.num.messages: 10000
  flush.timeout: -1
  retention.ms: -1
  consume.timeout: 5.0
  auto.offset.reset: earliest
  enable.auto.commit: true
  session.timeout.ms: 10000
  block.num.retries.int: 50
  block.interval: 0.1
