rest_proxy:
  rest.proxy.url: http://localhost:8082
#  basic.auth.user.info: 

schema_registry:
  schema.registry.url: http://localhost:8081

kash:
  auto.offset.reset: earliest
  enable.auto.commit: true
  fetch.min.bytes: -1
  consumer.request.timeout.ms: 1000
