name: Run Unit Tests with Coverage

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  run-test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt

      - name: Run custom test script
        working-directory: ${{github.workspace}}/test
        run: |
          # Run custom test script
          ./test.sh
    
      - name: Generate coverage report
        run: |
          coverage html
